[package]
name = "wasmersandbox"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.100"
socket2 = { version = "0.5.7", features = ["all"] }
wasmer = { version = "6.0.1", features = ["cranelift", "sys"] }
wasmer-wasix = { version = "0.600.1", default-features = false, features = ["sys"] }
