// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: daemon/apiv1/daemon.proto

package daemonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	apiv1 "github.com/solidarity-ai/toolbox/daemon/apiv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "toolbox.daemon.v1.SessionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServicePingProcedure is the fully-qualified name of the SessionService's Ping RPC.
	SessionServicePingProcedure = "/toolbox.daemon.v1.SessionService/Ping"
	// SessionServiceSyncStateProcedure is the fully-qualified name of the SessionService's SyncState
	// RPC.
	SessionServiceSyncStateProcedure = "/toolbox.daemon.v1.SessionService/SyncState"
)

// SessionServiceClient is a client for the toolbox.daemon.v1.SessionService service.
type SessionServiceClient interface {
	Ping(context.Context, *connect.Request[apiv1.PingRequest]) (*connect.Response[apiv1.PingResponse], error)
	SyncState(context.Context) *connect.BidiStreamForClient[apiv1.SessionState, apiv1.StateUpdate]
}

// NewSessionServiceClient constructs a client for the toolbox.daemon.v1.SessionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := apiv1.File_daemon_apiv1_daemon_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		ping: connect.NewClient[apiv1.PingRequest, apiv1.PingResponse](
			httpClient,
			baseURL+SessionServicePingProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		syncState: connect.NewClient[apiv1.SessionState, apiv1.StateUpdate](
			httpClient,
			baseURL+SessionServiceSyncStateProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SyncState")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	ping      *connect.Client[apiv1.PingRequest, apiv1.PingResponse]
	syncState *connect.Client[apiv1.SessionState, apiv1.StateUpdate]
}

// Ping calls toolbox.daemon.v1.SessionService.Ping.
func (c *sessionServiceClient) Ping(ctx context.Context, req *connect.Request[apiv1.PingRequest]) (*connect.Response[apiv1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// SyncState calls toolbox.daemon.v1.SessionService.SyncState.
func (c *sessionServiceClient) SyncState(ctx context.Context) *connect.BidiStreamForClient[apiv1.SessionState, apiv1.StateUpdate] {
	return c.syncState.CallBidiStream(ctx)
}

// SessionServiceHandler is an implementation of the toolbox.daemon.v1.SessionService service.
type SessionServiceHandler interface {
	Ping(context.Context, *connect.Request[apiv1.PingRequest]) (*connect.Response[apiv1.PingResponse], error)
	SyncState(context.Context, *connect.BidiStream[apiv1.SessionState, apiv1.StateUpdate]) error
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := apiv1.File_daemon_apiv1_daemon_proto.Services().ByName("SessionService").Methods()
	sessionServicePingHandler := connect.NewUnaryHandler(
		SessionServicePingProcedure,
		svc.Ping,
		connect.WithSchema(sessionServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSyncStateHandler := connect.NewBidiStreamHandler(
		SessionServiceSyncStateProcedure,
		svc.SyncState,
		connect.WithSchema(sessionServiceMethods.ByName("SyncState")),
		connect.WithHandlerOptions(opts...),
	)
	return "/toolbox.daemon.v1.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServicePingProcedure:
			sessionServicePingHandler.ServeHTTP(w, r)
		case SessionServiceSyncStateProcedure:
			sessionServiceSyncStateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) Ping(context.Context, *connect.Request[apiv1.PingRequest]) (*connect.Response[apiv1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SessionService.Ping is not implemented"))
}

func (UnimplementedSessionServiceHandler) SyncState(context.Context, *connect.BidiStream[apiv1.SessionState, apiv1.StateUpdate]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SessionService.SyncState is not implemented"))
}
