// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: daemon/apiv1/daemon.proto

package daemonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	apiv1 "github.com/solidarity-ai/toolbox/daemon/apiv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "toolbox.daemon.v1.SessionService"
	// SecretStoreServiceName is the fully-qualified name of the SecretStoreService service.
	SecretStoreServiceName = "toolbox.daemon.v1.SecretStoreService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServicePingProcedure is the fully-qualified name of the SessionService's Ping RPC.
	SessionServicePingProcedure = "/toolbox.daemon.v1.SessionService/Ping"
	// SessionServiceSyncStateProcedure is the fully-qualified name of the SessionService's SyncState
	// RPC.
	SessionServiceSyncStateProcedure = "/toolbox.daemon.v1.SessionService/SyncState"
	// SecretStoreServiceUnlockProcedure is the fully-qualified name of the SecretStoreService's Unlock
	// RPC.
	SecretStoreServiceUnlockProcedure = "/toolbox.daemon.v1.SecretStoreService/Unlock"
	// SecretStoreServiceSetupProcedure is the fully-qualified name of the SecretStoreService's Setup
	// RPC.
	SecretStoreServiceSetupProcedure = "/toolbox.daemon.v1.SecretStoreService/Setup"
	// SecretStoreServiceLockProcedure is the fully-qualified name of the SecretStoreService's Lock RPC.
	SecretStoreServiceLockProcedure = "/toolbox.daemon.v1.SecretStoreService/Lock"
	// SecretStoreServiceInitializedProcedure is the fully-qualified name of the SecretStoreService's
	// Initialized RPC.
	SecretStoreServiceInitializedProcedure = "/toolbox.daemon.v1.SecretStoreService/Initialized"
	// SecretStoreServiceBackupCodesProcedure is the fully-qualified name of the SecretStoreService's
	// BackupCodes RPC.
	SecretStoreServiceBackupCodesProcedure = "/toolbox.daemon.v1.SecretStoreService/BackupCodes"
	// SecretStoreServiceRecoveryCodesProcedure is the fully-qualified name of the SecretStoreService's
	// RecoveryCodes RPC.
	SecretStoreServiceRecoveryCodesProcedure = "/toolbox.daemon.v1.SecretStoreService/RecoveryCodes"
	// SecretStoreServiceRecoveryUnlockedProcedure is the fully-qualified name of the
	// SecretStoreService's RecoveryUnlocked RPC.
	SecretStoreServiceRecoveryUnlockedProcedure = "/toolbox.daemon.v1.SecretStoreService/RecoveryUnlocked"
	// SecretStoreServiceRewrapAfterRecoveryProcedure is the fully-qualified name of the
	// SecretStoreService's RewrapAfterRecovery RPC.
	SecretStoreServiceRewrapAfterRecoveryProcedure = "/toolbox.daemon.v1.SecretStoreService/RewrapAfterRecovery"
	// SecretStoreServiceGetProcedure is the fully-qualified name of the SecretStoreService's Get RPC.
	SecretStoreServiceGetProcedure = "/toolbox.daemon.v1.SecretStoreService/Get"
	// SecretStoreServiceSetProcedure is the fully-qualified name of the SecretStoreService's Set RPC.
	SecretStoreServiceSetProcedure = "/toolbox.daemon.v1.SecretStoreService/Set"
	// SecretStoreServiceDeleteProcedure is the fully-qualified name of the SecretStoreService's Delete
	// RPC.
	SecretStoreServiceDeleteProcedure = "/toolbox.daemon.v1.SecretStoreService/Delete"
	// SecretStoreServiceListProcedure is the fully-qualified name of the SecretStoreService's List RPC.
	SecretStoreServiceListProcedure = "/toolbox.daemon.v1.SecretStoreService/List"
)

// SessionServiceClient is a client for the toolbox.daemon.v1.SessionService service.
type SessionServiceClient interface {
	Ping(context.Context, *connect.Request[apiv1.PingRequest]) (*connect.Response[apiv1.PingResponse], error)
	SyncState(context.Context) *connect.BidiStreamForClient[apiv1.SessionState, apiv1.StateUpdate]
}

// NewSessionServiceClient constructs a client for the toolbox.daemon.v1.SessionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := apiv1.File_daemon_apiv1_daemon_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		ping: connect.NewClient[apiv1.PingRequest, apiv1.PingResponse](
			httpClient,
			baseURL+SessionServicePingProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		syncState: connect.NewClient[apiv1.SessionState, apiv1.StateUpdate](
			httpClient,
			baseURL+SessionServiceSyncStateProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SyncState")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	ping      *connect.Client[apiv1.PingRequest, apiv1.PingResponse]
	syncState *connect.Client[apiv1.SessionState, apiv1.StateUpdate]
}

// Ping calls toolbox.daemon.v1.SessionService.Ping.
func (c *sessionServiceClient) Ping(ctx context.Context, req *connect.Request[apiv1.PingRequest]) (*connect.Response[apiv1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// SyncState calls toolbox.daemon.v1.SessionService.SyncState.
func (c *sessionServiceClient) SyncState(ctx context.Context) *connect.BidiStreamForClient[apiv1.SessionState, apiv1.StateUpdate] {
	return c.syncState.CallBidiStream(ctx)
}

// SessionServiceHandler is an implementation of the toolbox.daemon.v1.SessionService service.
type SessionServiceHandler interface {
	Ping(context.Context, *connect.Request[apiv1.PingRequest]) (*connect.Response[apiv1.PingResponse], error)
	SyncState(context.Context, *connect.BidiStream[apiv1.SessionState, apiv1.StateUpdate]) error
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := apiv1.File_daemon_apiv1_daemon_proto.Services().ByName("SessionService").Methods()
	sessionServicePingHandler := connect.NewUnaryHandler(
		SessionServicePingProcedure,
		svc.Ping,
		connect.WithSchema(sessionServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSyncStateHandler := connect.NewBidiStreamHandler(
		SessionServiceSyncStateProcedure,
		svc.SyncState,
		connect.WithSchema(sessionServiceMethods.ByName("SyncState")),
		connect.WithHandlerOptions(opts...),
	)
	return "/toolbox.daemon.v1.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServicePingProcedure:
			sessionServicePingHandler.ServeHTTP(w, r)
		case SessionServiceSyncStateProcedure:
			sessionServiceSyncStateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) Ping(context.Context, *connect.Request[apiv1.PingRequest]) (*connect.Response[apiv1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SessionService.Ping is not implemented"))
}

func (UnimplementedSessionServiceHandler) SyncState(context.Context, *connect.BidiStream[apiv1.SessionState, apiv1.StateUpdate]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SessionService.SyncState is not implemented"))
}

// SecretStoreServiceClient is a client for the toolbox.daemon.v1.SecretStoreService service.
type SecretStoreServiceClient interface {
	Unlock(context.Context, *connect.Request[apiv1.SecretUnlockRequest]) (*connect.Response[apiv1.SecretUnlockResponse], error)
	Setup(context.Context, *connect.Request[apiv1.SecretSetupRequest]) (*connect.Response[apiv1.SecretSetupResponse], error)
	Lock(context.Context, *connect.Request[apiv1.SecretLockRequest]) (*connect.Response[apiv1.SecretLockResponse], error)
	Initialized(context.Context, *connect.Request[apiv1.SecretInitializedRequest]) (*connect.Response[apiv1.SecretInitializedResponse], error)
	BackupCodes(context.Context, *connect.Request[apiv1.SecretBackupCodesRequest]) (*connect.Response[apiv1.SecretBackupCodesResponse], error)
	RecoveryCodes(context.Context, *connect.Request[apiv1.SecretRecoveryCodesRequest]) (*connect.Response[apiv1.SecretRecoveryCodesResponse], error)
	RecoveryUnlocked(context.Context, *connect.Request[apiv1.SecretRecoveryUnlockedRequest]) (*connect.Response[apiv1.SecretRecoveryUnlockedResponse], error)
	RewrapAfterRecovery(context.Context, *connect.Request[apiv1.SecretRewrapAfterRecoveryRequest]) (*connect.Response[apiv1.SecretRewrapAfterRecoveryResponse], error)
	Get(context.Context, *connect.Request[apiv1.SecretGetRequest]) (*connect.Response[apiv1.SecretGetResponse], error)
	Set(context.Context, *connect.Request[apiv1.SecretSetRequest]) (*connect.Response[apiv1.SecretSetResponse], error)
	Delete(context.Context, *connect.Request[apiv1.SecretDeleteRequest]) (*connect.Response[apiv1.SecretDeleteResponse], error)
	List(context.Context, *connect.Request[apiv1.SecretListRequest]) (*connect.Response[apiv1.SecretListResponse], error)
}

// NewSecretStoreServiceClient constructs a client for the toolbox.daemon.v1.SecretStoreService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSecretStoreServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SecretStoreServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	secretStoreServiceMethods := apiv1.File_daemon_apiv1_daemon_proto.Services().ByName("SecretStoreService").Methods()
	return &secretStoreServiceClient{
		unlock: connect.NewClient[apiv1.SecretUnlockRequest, apiv1.SecretUnlockResponse](
			httpClient,
			baseURL+SecretStoreServiceUnlockProcedure,
			connect.WithSchema(secretStoreServiceMethods.ByName("Unlock")),
			connect.WithClientOptions(opts...),
		),
		setup: connect.NewClient[apiv1.SecretSetupRequest, apiv1.SecretSetupResponse](
			httpClient,
			baseURL+SecretStoreServiceSetupProcedure,
			connect.WithSchema(secretStoreServiceMethods.ByName("Setup")),
			connect.WithClientOptions(opts...),
		),
		lock: connect.NewClient[apiv1.SecretLockRequest, apiv1.SecretLockResponse](
			httpClient,
			baseURL+SecretStoreServiceLockProcedure,
			connect.WithSchema(secretStoreServiceMethods.ByName("Lock")),
			connect.WithClientOptions(opts...),
		),
		initialized: connect.NewClient[apiv1.SecretInitializedRequest, apiv1.SecretInitializedResponse](
			httpClient,
			baseURL+SecretStoreServiceInitializedProcedure,
			connect.WithSchema(secretStoreServiceMethods.ByName("Initialized")),
			connect.WithClientOptions(opts...),
		),
		backupCodes: connect.NewClient[apiv1.SecretBackupCodesRequest, apiv1.SecretBackupCodesResponse](
			httpClient,
			baseURL+SecretStoreServiceBackupCodesProcedure,
			connect.WithSchema(secretStoreServiceMethods.ByName("BackupCodes")),
			connect.WithClientOptions(opts...),
		),
		recoveryCodes: connect.NewClient[apiv1.SecretRecoveryCodesRequest, apiv1.SecretRecoveryCodesResponse](
			httpClient,
			baseURL+SecretStoreServiceRecoveryCodesProcedure,
			connect.WithSchema(secretStoreServiceMethods.ByName("RecoveryCodes")),
			connect.WithClientOptions(opts...),
		),
		recoveryUnlocked: connect.NewClient[apiv1.SecretRecoveryUnlockedRequest, apiv1.SecretRecoveryUnlockedResponse](
			httpClient,
			baseURL+SecretStoreServiceRecoveryUnlockedProcedure,
			connect.WithSchema(secretStoreServiceMethods.ByName("RecoveryUnlocked")),
			connect.WithClientOptions(opts...),
		),
		rewrapAfterRecovery: connect.NewClient[apiv1.SecretRewrapAfterRecoveryRequest, apiv1.SecretRewrapAfterRecoveryResponse](
			httpClient,
			baseURL+SecretStoreServiceRewrapAfterRecoveryProcedure,
			connect.WithSchema(secretStoreServiceMethods.ByName("RewrapAfterRecovery")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[apiv1.SecretGetRequest, apiv1.SecretGetResponse](
			httpClient,
			baseURL+SecretStoreServiceGetProcedure,
			connect.WithSchema(secretStoreServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		set: connect.NewClient[apiv1.SecretSetRequest, apiv1.SecretSetResponse](
			httpClient,
			baseURL+SecretStoreServiceSetProcedure,
			connect.WithSchema(secretStoreServiceMethods.ByName("Set")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[apiv1.SecretDeleteRequest, apiv1.SecretDeleteResponse](
			httpClient,
			baseURL+SecretStoreServiceDeleteProcedure,
			connect.WithSchema(secretStoreServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[apiv1.SecretListRequest, apiv1.SecretListResponse](
			httpClient,
			baseURL+SecretStoreServiceListProcedure,
			connect.WithSchema(secretStoreServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
	}
}

// secretStoreServiceClient implements SecretStoreServiceClient.
type secretStoreServiceClient struct {
	unlock              *connect.Client[apiv1.SecretUnlockRequest, apiv1.SecretUnlockResponse]
	setup               *connect.Client[apiv1.SecretSetupRequest, apiv1.SecretSetupResponse]
	lock                *connect.Client[apiv1.SecretLockRequest, apiv1.SecretLockResponse]
	initialized         *connect.Client[apiv1.SecretInitializedRequest, apiv1.SecretInitializedResponse]
	backupCodes         *connect.Client[apiv1.SecretBackupCodesRequest, apiv1.SecretBackupCodesResponse]
	recoveryCodes       *connect.Client[apiv1.SecretRecoveryCodesRequest, apiv1.SecretRecoveryCodesResponse]
	recoveryUnlocked    *connect.Client[apiv1.SecretRecoveryUnlockedRequest, apiv1.SecretRecoveryUnlockedResponse]
	rewrapAfterRecovery *connect.Client[apiv1.SecretRewrapAfterRecoveryRequest, apiv1.SecretRewrapAfterRecoveryResponse]
	get                 *connect.Client[apiv1.SecretGetRequest, apiv1.SecretGetResponse]
	set                 *connect.Client[apiv1.SecretSetRequest, apiv1.SecretSetResponse]
	delete              *connect.Client[apiv1.SecretDeleteRequest, apiv1.SecretDeleteResponse]
	list                *connect.Client[apiv1.SecretListRequest, apiv1.SecretListResponse]
}

// Unlock calls toolbox.daemon.v1.SecretStoreService.Unlock.
func (c *secretStoreServiceClient) Unlock(ctx context.Context, req *connect.Request[apiv1.SecretUnlockRequest]) (*connect.Response[apiv1.SecretUnlockResponse], error) {
	return c.unlock.CallUnary(ctx, req)
}

// Setup calls toolbox.daemon.v1.SecretStoreService.Setup.
func (c *secretStoreServiceClient) Setup(ctx context.Context, req *connect.Request[apiv1.SecretSetupRequest]) (*connect.Response[apiv1.SecretSetupResponse], error) {
	return c.setup.CallUnary(ctx, req)
}

// Lock calls toolbox.daemon.v1.SecretStoreService.Lock.
func (c *secretStoreServiceClient) Lock(ctx context.Context, req *connect.Request[apiv1.SecretLockRequest]) (*connect.Response[apiv1.SecretLockResponse], error) {
	return c.lock.CallUnary(ctx, req)
}

// Initialized calls toolbox.daemon.v1.SecretStoreService.Initialized.
func (c *secretStoreServiceClient) Initialized(ctx context.Context, req *connect.Request[apiv1.SecretInitializedRequest]) (*connect.Response[apiv1.SecretInitializedResponse], error) {
	return c.initialized.CallUnary(ctx, req)
}

// BackupCodes calls toolbox.daemon.v1.SecretStoreService.BackupCodes.
func (c *secretStoreServiceClient) BackupCodes(ctx context.Context, req *connect.Request[apiv1.SecretBackupCodesRequest]) (*connect.Response[apiv1.SecretBackupCodesResponse], error) {
	return c.backupCodes.CallUnary(ctx, req)
}

// RecoveryCodes calls toolbox.daemon.v1.SecretStoreService.RecoveryCodes.
func (c *secretStoreServiceClient) RecoveryCodes(ctx context.Context, req *connect.Request[apiv1.SecretRecoveryCodesRequest]) (*connect.Response[apiv1.SecretRecoveryCodesResponse], error) {
	return c.recoveryCodes.CallUnary(ctx, req)
}

// RecoveryUnlocked calls toolbox.daemon.v1.SecretStoreService.RecoveryUnlocked.
func (c *secretStoreServiceClient) RecoveryUnlocked(ctx context.Context, req *connect.Request[apiv1.SecretRecoveryUnlockedRequest]) (*connect.Response[apiv1.SecretRecoveryUnlockedResponse], error) {
	return c.recoveryUnlocked.CallUnary(ctx, req)
}

// RewrapAfterRecovery calls toolbox.daemon.v1.SecretStoreService.RewrapAfterRecovery.
func (c *secretStoreServiceClient) RewrapAfterRecovery(ctx context.Context, req *connect.Request[apiv1.SecretRewrapAfterRecoveryRequest]) (*connect.Response[apiv1.SecretRewrapAfterRecoveryResponse], error) {
	return c.rewrapAfterRecovery.CallUnary(ctx, req)
}

// Get calls toolbox.daemon.v1.SecretStoreService.Get.
func (c *secretStoreServiceClient) Get(ctx context.Context, req *connect.Request[apiv1.SecretGetRequest]) (*connect.Response[apiv1.SecretGetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Set calls toolbox.daemon.v1.SecretStoreService.Set.
func (c *secretStoreServiceClient) Set(ctx context.Context, req *connect.Request[apiv1.SecretSetRequest]) (*connect.Response[apiv1.SecretSetResponse], error) {
	return c.set.CallUnary(ctx, req)
}

// Delete calls toolbox.daemon.v1.SecretStoreService.Delete.
func (c *secretStoreServiceClient) Delete(ctx context.Context, req *connect.Request[apiv1.SecretDeleteRequest]) (*connect.Response[apiv1.SecretDeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls toolbox.daemon.v1.SecretStoreService.List.
func (c *secretStoreServiceClient) List(ctx context.Context, req *connect.Request[apiv1.SecretListRequest]) (*connect.Response[apiv1.SecretListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// SecretStoreServiceHandler is an implementation of the toolbox.daemon.v1.SecretStoreService
// service.
type SecretStoreServiceHandler interface {
	Unlock(context.Context, *connect.Request[apiv1.SecretUnlockRequest]) (*connect.Response[apiv1.SecretUnlockResponse], error)
	Setup(context.Context, *connect.Request[apiv1.SecretSetupRequest]) (*connect.Response[apiv1.SecretSetupResponse], error)
	Lock(context.Context, *connect.Request[apiv1.SecretLockRequest]) (*connect.Response[apiv1.SecretLockResponse], error)
	Initialized(context.Context, *connect.Request[apiv1.SecretInitializedRequest]) (*connect.Response[apiv1.SecretInitializedResponse], error)
	BackupCodes(context.Context, *connect.Request[apiv1.SecretBackupCodesRequest]) (*connect.Response[apiv1.SecretBackupCodesResponse], error)
	RecoveryCodes(context.Context, *connect.Request[apiv1.SecretRecoveryCodesRequest]) (*connect.Response[apiv1.SecretRecoveryCodesResponse], error)
	RecoveryUnlocked(context.Context, *connect.Request[apiv1.SecretRecoveryUnlockedRequest]) (*connect.Response[apiv1.SecretRecoveryUnlockedResponse], error)
	RewrapAfterRecovery(context.Context, *connect.Request[apiv1.SecretRewrapAfterRecoveryRequest]) (*connect.Response[apiv1.SecretRewrapAfterRecoveryResponse], error)
	Get(context.Context, *connect.Request[apiv1.SecretGetRequest]) (*connect.Response[apiv1.SecretGetResponse], error)
	Set(context.Context, *connect.Request[apiv1.SecretSetRequest]) (*connect.Response[apiv1.SecretSetResponse], error)
	Delete(context.Context, *connect.Request[apiv1.SecretDeleteRequest]) (*connect.Response[apiv1.SecretDeleteResponse], error)
	List(context.Context, *connect.Request[apiv1.SecretListRequest]) (*connect.Response[apiv1.SecretListResponse], error)
}

// NewSecretStoreServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSecretStoreServiceHandler(svc SecretStoreServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	secretStoreServiceMethods := apiv1.File_daemon_apiv1_daemon_proto.Services().ByName("SecretStoreService").Methods()
	secretStoreServiceUnlockHandler := connect.NewUnaryHandler(
		SecretStoreServiceUnlockProcedure,
		svc.Unlock,
		connect.WithSchema(secretStoreServiceMethods.ByName("Unlock")),
		connect.WithHandlerOptions(opts...),
	)
	secretStoreServiceSetupHandler := connect.NewUnaryHandler(
		SecretStoreServiceSetupProcedure,
		svc.Setup,
		connect.WithSchema(secretStoreServiceMethods.ByName("Setup")),
		connect.WithHandlerOptions(opts...),
	)
	secretStoreServiceLockHandler := connect.NewUnaryHandler(
		SecretStoreServiceLockProcedure,
		svc.Lock,
		connect.WithSchema(secretStoreServiceMethods.ByName("Lock")),
		connect.WithHandlerOptions(opts...),
	)
	secretStoreServiceInitializedHandler := connect.NewUnaryHandler(
		SecretStoreServiceInitializedProcedure,
		svc.Initialized,
		connect.WithSchema(secretStoreServiceMethods.ByName("Initialized")),
		connect.WithHandlerOptions(opts...),
	)
	secretStoreServiceBackupCodesHandler := connect.NewUnaryHandler(
		SecretStoreServiceBackupCodesProcedure,
		svc.BackupCodes,
		connect.WithSchema(secretStoreServiceMethods.ByName("BackupCodes")),
		connect.WithHandlerOptions(opts...),
	)
	secretStoreServiceRecoveryCodesHandler := connect.NewUnaryHandler(
		SecretStoreServiceRecoveryCodesProcedure,
		svc.RecoveryCodes,
		connect.WithSchema(secretStoreServiceMethods.ByName("RecoveryCodes")),
		connect.WithHandlerOptions(opts...),
	)
	secretStoreServiceRecoveryUnlockedHandler := connect.NewUnaryHandler(
		SecretStoreServiceRecoveryUnlockedProcedure,
		svc.RecoveryUnlocked,
		connect.WithSchema(secretStoreServiceMethods.ByName("RecoveryUnlocked")),
		connect.WithHandlerOptions(opts...),
	)
	secretStoreServiceRewrapAfterRecoveryHandler := connect.NewUnaryHandler(
		SecretStoreServiceRewrapAfterRecoveryProcedure,
		svc.RewrapAfterRecovery,
		connect.WithSchema(secretStoreServiceMethods.ByName("RewrapAfterRecovery")),
		connect.WithHandlerOptions(opts...),
	)
	secretStoreServiceGetHandler := connect.NewUnaryHandler(
		SecretStoreServiceGetProcedure,
		svc.Get,
		connect.WithSchema(secretStoreServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	secretStoreServiceSetHandler := connect.NewUnaryHandler(
		SecretStoreServiceSetProcedure,
		svc.Set,
		connect.WithSchema(secretStoreServiceMethods.ByName("Set")),
		connect.WithHandlerOptions(opts...),
	)
	secretStoreServiceDeleteHandler := connect.NewUnaryHandler(
		SecretStoreServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(secretStoreServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	secretStoreServiceListHandler := connect.NewUnaryHandler(
		SecretStoreServiceListProcedure,
		svc.List,
		connect.WithSchema(secretStoreServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	return "/toolbox.daemon.v1.SecretStoreService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SecretStoreServiceUnlockProcedure:
			secretStoreServiceUnlockHandler.ServeHTTP(w, r)
		case SecretStoreServiceSetupProcedure:
			secretStoreServiceSetupHandler.ServeHTTP(w, r)
		case SecretStoreServiceLockProcedure:
			secretStoreServiceLockHandler.ServeHTTP(w, r)
		case SecretStoreServiceInitializedProcedure:
			secretStoreServiceInitializedHandler.ServeHTTP(w, r)
		case SecretStoreServiceBackupCodesProcedure:
			secretStoreServiceBackupCodesHandler.ServeHTTP(w, r)
		case SecretStoreServiceRecoveryCodesProcedure:
			secretStoreServiceRecoveryCodesHandler.ServeHTTP(w, r)
		case SecretStoreServiceRecoveryUnlockedProcedure:
			secretStoreServiceRecoveryUnlockedHandler.ServeHTTP(w, r)
		case SecretStoreServiceRewrapAfterRecoveryProcedure:
			secretStoreServiceRewrapAfterRecoveryHandler.ServeHTTP(w, r)
		case SecretStoreServiceGetProcedure:
			secretStoreServiceGetHandler.ServeHTTP(w, r)
		case SecretStoreServiceSetProcedure:
			secretStoreServiceSetHandler.ServeHTTP(w, r)
		case SecretStoreServiceDeleteProcedure:
			secretStoreServiceDeleteHandler.ServeHTTP(w, r)
		case SecretStoreServiceListProcedure:
			secretStoreServiceListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSecretStoreServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSecretStoreServiceHandler struct{}

func (UnimplementedSecretStoreServiceHandler) Unlock(context.Context, *connect.Request[apiv1.SecretUnlockRequest]) (*connect.Response[apiv1.SecretUnlockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SecretStoreService.Unlock is not implemented"))
}

func (UnimplementedSecretStoreServiceHandler) Setup(context.Context, *connect.Request[apiv1.SecretSetupRequest]) (*connect.Response[apiv1.SecretSetupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SecretStoreService.Setup is not implemented"))
}

func (UnimplementedSecretStoreServiceHandler) Lock(context.Context, *connect.Request[apiv1.SecretLockRequest]) (*connect.Response[apiv1.SecretLockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SecretStoreService.Lock is not implemented"))
}

func (UnimplementedSecretStoreServiceHandler) Initialized(context.Context, *connect.Request[apiv1.SecretInitializedRequest]) (*connect.Response[apiv1.SecretInitializedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SecretStoreService.Initialized is not implemented"))
}

func (UnimplementedSecretStoreServiceHandler) BackupCodes(context.Context, *connect.Request[apiv1.SecretBackupCodesRequest]) (*connect.Response[apiv1.SecretBackupCodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SecretStoreService.BackupCodes is not implemented"))
}

func (UnimplementedSecretStoreServiceHandler) RecoveryCodes(context.Context, *connect.Request[apiv1.SecretRecoveryCodesRequest]) (*connect.Response[apiv1.SecretRecoveryCodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SecretStoreService.RecoveryCodes is not implemented"))
}

func (UnimplementedSecretStoreServiceHandler) RecoveryUnlocked(context.Context, *connect.Request[apiv1.SecretRecoveryUnlockedRequest]) (*connect.Response[apiv1.SecretRecoveryUnlockedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SecretStoreService.RecoveryUnlocked is not implemented"))
}

func (UnimplementedSecretStoreServiceHandler) RewrapAfterRecovery(context.Context, *connect.Request[apiv1.SecretRewrapAfterRecoveryRequest]) (*connect.Response[apiv1.SecretRewrapAfterRecoveryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SecretStoreService.RewrapAfterRecovery is not implemented"))
}

func (UnimplementedSecretStoreServiceHandler) Get(context.Context, *connect.Request[apiv1.SecretGetRequest]) (*connect.Response[apiv1.SecretGetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SecretStoreService.Get is not implemented"))
}

func (UnimplementedSecretStoreServiceHandler) Set(context.Context, *connect.Request[apiv1.SecretSetRequest]) (*connect.Response[apiv1.SecretSetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SecretStoreService.Set is not implemented"))
}

func (UnimplementedSecretStoreServiceHandler) Delete(context.Context, *connect.Request[apiv1.SecretDeleteRequest]) (*connect.Response[apiv1.SecretDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SecretStoreService.Delete is not implemented"))
}

func (UnimplementedSecretStoreServiceHandler) List(context.Context, *connect.Request[apiv1.SecretListRequest]) (*connect.Response[apiv1.SecretListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("toolbox.daemon.v1.SecretStoreService.List is not implemented"))
}
