// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: daemon/apiv1/daemon.proto

package daemonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *PingResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type SessionState struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Pid              int32                      `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Mode             string                     `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	WorkingDir       string                     `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	PreparedTools    []string                   `protobuf:"bytes,4,rep,name=prepared_tools,json=preparedTools,proto3" json:"prepared_tools,omitempty"`
	PendingApprovals []*PendingApprovalSnapshot `protobuf:"bytes,5,rep,name=pending_approvals,json=pendingApprovals,proto3" json:"pending_approvals,omitempty"`
	Locked           bool                       `protobuf:"varint,6,opt,name=locked,proto3" json:"locked,omitempty"`
	BoundTbSession   string                     `protobuf:"bytes,7,opt,name=bound_tb_session,json=boundTbSession,proto3" json:"bound_tb_session,omitempty"`
	IntentText       string                     `protobuf:"bytes,8,opt,name=intent_text,json=intentText,proto3" json:"intent_text,omitempty"`
	IntentSource     string                     `protobuf:"bytes,9,opt,name=intent_source,json=intentSource,proto3" json:"intent_source,omitempty"`
	IntentUpdatedAt  string                     `protobuf:"bytes,10,opt,name=intent_updated_at,json=intentUpdatedAt,proto3" json:"intent_updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionState) Reset() {
	*x = SessionState{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionState) ProtoMessage() {}

func (x *SessionState) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionState.ProtoReflect.Descriptor instead.
func (*SessionState) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *SessionState) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SessionState) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SessionState) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *SessionState) GetPreparedTools() []string {
	if x != nil {
		return x.PreparedTools
	}
	return nil
}

func (x *SessionState) GetPendingApprovals() []*PendingApprovalSnapshot {
	if x != nil {
		return x.PendingApprovals
	}
	return nil
}

func (x *SessionState) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *SessionState) GetBoundTbSession() string {
	if x != nil {
		return x.BoundTbSession
	}
	return ""
}

func (x *SessionState) GetIntentText() string {
	if x != nil {
		return x.IntentText
	}
	return ""
}

func (x *SessionState) GetIntentSource() string {
	if x != nil {
		return x.IntentSource
	}
	return ""
}

func (x *SessionState) GetIntentUpdatedAt() string {
	if x != nil {
		return x.IntentUpdatedAt
	}
	return ""
}

type PendingApprovalSnapshot struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId          string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName            string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ParamsInspect       string                 `protobuf:"bytes,3,opt,name=params_inspect,json=paramsInspect,proto3" json:"params_inspect,omitempty"`
	EffectId            string                 `protobuf:"bytes,4,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	Status              string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Error               string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	TbSession           string                 `protobuf:"bytes,7,opt,name=tb_session,json=tbSession,proto3" json:"tb_session,omitempty"`
	CellId              string                 `protobuf:"bytes,8,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	FullToolName        string                 `protobuf:"bytes,9,opt,name=full_tool_name,json=fullToolName,proto3" json:"full_tool_name,omitempty"`
	PackageKey          string                 `protobuf:"bytes,10,opt,name=package_key,json=packageKey,proto3" json:"package_key,omitempty"`
	PackageLabel        string                 `protobuf:"bytes,11,opt,name=package_label,json=packageLabel,proto3" json:"package_label,omitempty"`
	ToolLabel           string                 `protobuf:"bytes,12,opt,name=tool_label,json=toolLabel,proto3" json:"tool_label,omitempty"`
	Description         string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	Presentation        string                 `protobuf:"bytes,14,opt,name=presentation,proto3" json:"presentation,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IntentText          string                 `protobuf:"bytes,17,opt,name=intent_text,json=intentText,proto3" json:"intent_text,omitempty"`
	IntentSource        string                 `protobuf:"bytes,18,opt,name=intent_source,json=intentSource,proto3" json:"intent_source,omitempty"`
	IntentUpdatedAt     string                 `protobuf:"bytes,19,opt,name=intent_updated_at,json=intentUpdatedAt,proto3" json:"intent_updated_at,omitempty"`
	RequiresCredentials bool                   `protobuf:"varint,20,opt,name=requires_credentials,json=requiresCredentials,proto3" json:"requires_credentials,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PendingApprovalSnapshot) Reset() {
	*x = PendingApprovalSnapshot{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingApprovalSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingApprovalSnapshot) ProtoMessage() {}

func (x *PendingApprovalSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingApprovalSnapshot.ProtoReflect.Descriptor instead.
func (*PendingApprovalSnapshot) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *PendingApprovalSnapshot) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetParamsInspect() string {
	if x != nil {
		return x.ParamsInspect
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetTbSession() string {
	if x != nil {
		return x.TbSession
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetFullToolName() string {
	if x != nil {
		return x.FullToolName
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetPackageKey() string {
	if x != nil {
		return x.PackageKey
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetPackageLabel() string {
	if x != nil {
		return x.PackageLabel
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetToolLabel() string {
	if x != nil {
		return x.ToolLabel
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetPresentation() string {
	if x != nil {
		return x.Presentation
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetIntentText() string {
	if x != nil {
		return x.IntentText
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetIntentSource() string {
	if x != nil {
		return x.IntentSource
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetIntentUpdatedAt() string {
	if x != nil {
		return x.IntentUpdatedAt
	}
	return ""
}

func (x *PendingApprovalSnapshot) GetRequiresCredentials() bool {
	if x != nil {
		return x.RequiresCredentials
	}
	return false
}

type ApprovalDecision struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Action           string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	ToolCallId       string                 `protobuf:"bytes,2,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ClientDecisionId string                 `protobuf:"bytes,4,opt,name=client_decision_id,json=clientDecisionId,proto3" json:"client_decision_id,omitempty"`
	QueuedAt         string                 `protobuf:"bytes,5,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApprovalDecision) Reset() {
	*x = ApprovalDecision{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalDecision) ProtoMessage() {}

func (x *ApprovalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalDecision.ProtoReflect.Descriptor instead.
func (*ApprovalDecision) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *ApprovalDecision) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ApprovalDecision) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ApprovalDecision) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApprovalDecision) GetClientDecisionId() string {
	if x != nil {
		return x.ClientDecisionId
	}
	return ""
}

func (x *ApprovalDecision) GetQueuedAt() string {
	if x != nil {
		return x.QueuedAt
	}
	return ""
}

type ClientSnapshot struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Pid              int32                      `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Mode             string                     `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	WorkingDir       string                     `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	PreparedTools    []string                   `protobuf:"bytes,4,rep,name=prepared_tools,json=preparedTools,proto3" json:"prepared_tools,omitempty"`
	ConnectedAt      *timestamppb.Timestamp     `protobuf:"bytes,5,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	LastSyncAt       *timestamppb.Timestamp     `protobuf:"bytes,6,opt,name=last_sync_at,json=lastSyncAt,proto3" json:"last_sync_at,omitempty"`
	PendingApprovals []*PendingApprovalSnapshot `protobuf:"bytes,7,rep,name=pending_approvals,json=pendingApprovals,proto3" json:"pending_approvals,omitempty"`
	Locked           bool                       `protobuf:"varint,8,opt,name=locked,proto3" json:"locked,omitempty"`
	BoundTbSession   string                     `protobuf:"bytes,9,opt,name=bound_tb_session,json=boundTbSession,proto3" json:"bound_tb_session,omitempty"`
	IntentText       string                     `protobuf:"bytes,10,opt,name=intent_text,json=intentText,proto3" json:"intent_text,omitempty"`
	IntentSource     string                     `protobuf:"bytes,11,opt,name=intent_source,json=intentSource,proto3" json:"intent_source,omitempty"`
	IntentUpdatedAt  string                     `protobuf:"bytes,12,opt,name=intent_updated_at,json=intentUpdatedAt,proto3" json:"intent_updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientSnapshot) Reset() {
	*x = ClientSnapshot{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSnapshot) ProtoMessage() {}

func (x *ClientSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSnapshot.ProtoReflect.Descriptor instead.
func (*ClientSnapshot) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *ClientSnapshot) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ClientSnapshot) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ClientSnapshot) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ClientSnapshot) GetPreparedTools() []string {
	if x != nil {
		return x.PreparedTools
	}
	return nil
}

func (x *ClientSnapshot) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *ClientSnapshot) GetLastSyncAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncAt
	}
	return nil
}

func (x *ClientSnapshot) GetPendingApprovals() []*PendingApprovalSnapshot {
	if x != nil {
		return x.PendingApprovals
	}
	return nil
}

func (x *ClientSnapshot) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *ClientSnapshot) GetBoundTbSession() string {
	if x != nil {
		return x.BoundTbSession
	}
	return ""
}

func (x *ClientSnapshot) GetIntentText() string {
	if x != nil {
		return x.IntentText
	}
	return ""
}

func (x *ClientSnapshot) GetIntentSource() string {
	if x != nil {
		return x.IntentSource
	}
	return ""
}

func (x *ClientSnapshot) GetIntentUpdatedAt() string {
	if x != nil {
		return x.IntentUpdatedAt
	}
	return ""
}

type StateUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Clients           []*ClientSnapshot      `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	SecretEpoch       string                 `protobuf:"bytes,2,opt,name=secret_epoch,json=secretEpoch,proto3" json:"secret_epoch,omitempty"`
	ApprovalDecisions []*ApprovalDecision    `protobuf:"bytes,3,rep,name=approval_decisions,json=approvalDecisions,proto3" json:"approval_decisions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *StateUpdate) GetClients() []*ClientSnapshot {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *StateUpdate) GetSecretEpoch() string {
	if x != nil {
		return x.SecretEpoch
	}
	return ""
}

func (x *StateUpdate) GetApprovalDecisions() []*ApprovalDecision {
	if x != nil {
		return x.ApprovalDecisions
	}
	return nil
}

type SecretGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretGetRequest) Reset() {
	*x = SecretGetRequest{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretGetRequest) ProtoMessage() {}

func (x *SecretGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretGetRequest.ProtoReflect.Descriptor instead.
func (*SecretGetRequest) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *SecretGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SecretGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretGetResponse) Reset() {
	*x = SecretGetResponse{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretGetResponse) ProtoMessage() {}

func (x *SecretGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretGetResponse.ProtoReflect.Descriptor instead.
func (*SecretGetResponse) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *SecretGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SecretSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretSetRequest) Reset() {
	*x = SecretSetRequest{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretSetRequest) ProtoMessage() {}

func (x *SecretSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretSetRequest.ProtoReflect.Descriptor instead.
func (*SecretSetRequest) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *SecretSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SecretSetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SecretSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretSetResponse) Reset() {
	*x = SecretSetResponse{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretSetResponse) ProtoMessage() {}

func (x *SecretSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretSetResponse.ProtoReflect.Descriptor instead.
func (*SecretSetResponse) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{10}
}

type SecretDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretDeleteRequest) Reset() {
	*x = SecretDeleteRequest{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretDeleteRequest) ProtoMessage() {}

func (x *SecretDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretDeleteRequest.ProtoReflect.Descriptor instead.
func (*SecretDeleteRequest) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *SecretDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SecretDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretDeleteResponse) Reset() {
	*x = SecretDeleteResponse{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretDeleteResponse) ProtoMessage() {}

func (x *SecretDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretDeleteResponse.ProtoReflect.Descriptor instead.
func (*SecretDeleteResponse) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{12}
}

type SecretListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretListRequest) Reset() {
	*x = SecretListRequest{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretListRequest) ProtoMessage() {}

func (x *SecretListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretListRequest.ProtoReflect.Descriptor instead.
func (*SecretListRequest) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *SecretListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type SecretListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretListResponse) Reset() {
	*x = SecretListResponse{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretListResponse) ProtoMessage() {}

func (x *SecretListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretListResponse.ProtoReflect.Descriptor instead.
func (*SecretListResponse) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *SecretListResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SecretUnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnlockKey     string                 `protobuf:"bytes,1,opt,name=unlock_key,json=unlockKey,proto3" json:"unlock_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretUnlockRequest) Reset() {
	*x = SecretUnlockRequest{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretUnlockRequest) ProtoMessage() {}

func (x *SecretUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretUnlockRequest.ProtoReflect.Descriptor instead.
func (*SecretUnlockRequest) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *SecretUnlockRequest) GetUnlockKey() string {
	if x != nil {
		return x.UnlockKey
	}
	return ""
}

type SecretUnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretUnlockResponse) Reset() {
	*x = SecretUnlockResponse{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretUnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretUnlockResponse) ProtoMessage() {}

func (x *SecretUnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretUnlockResponse.ProtoReflect.Descriptor instead.
func (*SecretUnlockResponse) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{16}
}

type SecretSetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnlockKey     string                 `protobuf:"bytes,1,opt,name=unlock_key,json=unlockKey,proto3" json:"unlock_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretSetupRequest) Reset() {
	*x = SecretSetupRequest{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretSetupRequest) ProtoMessage() {}

func (x *SecretSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretSetupRequest.ProtoReflect.Descriptor instead.
func (*SecretSetupRequest) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *SecretSetupRequest) GetUnlockKey() string {
	if x != nil {
		return x.UnlockKey
	}
	return ""
}

type SecretSetupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupCodes   []string               `protobuf:"bytes,1,rep,name=backup_codes,json=backupCodes,proto3" json:"backup_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretSetupResponse) Reset() {
	*x = SecretSetupResponse{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretSetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretSetupResponse) ProtoMessage() {}

func (x *SecretSetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretSetupResponse.ProtoReflect.Descriptor instead.
func (*SecretSetupResponse) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *SecretSetupResponse) GetBackupCodes() []string {
	if x != nil {
		return x.BackupCodes
	}
	return nil
}

type SecretLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretLockRequest) Reset() {
	*x = SecretLockRequest{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretLockRequest) ProtoMessage() {}

func (x *SecretLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretLockRequest.ProtoReflect.Descriptor instead.
func (*SecretLockRequest) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{19}
}

type SecretLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretLockResponse) Reset() {
	*x = SecretLockResponse{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretLockResponse) ProtoMessage() {}

func (x *SecretLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretLockResponse.ProtoReflect.Descriptor instead.
func (*SecretLockResponse) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{20}
}

var File_daemon_apiv1_daemon_proto protoreflect.FileDescriptor

const file_daemon_apiv1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x19daemon/apiv1/daemon.proto\x12\x11toolbox.daemon.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vPingRequest\":\n" +
	"\fPingResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\"\x89\x03\n" +
	"\fSessionState\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12%\n" +
	"\x0eprepared_tools\x18\x04 \x03(\tR\rpreparedTools\x12W\n" +
	"\x11pending_approvals\x18\x05 \x03(\v2*.toolbox.daemon.v1.PendingApprovalSnapshotR\x10pendingApprovals\x12\x16\n" +
	"\x06locked\x18\x06 \x01(\bR\x06locked\x12(\n" +
	"\x10bound_tb_session\x18\a \x01(\tR\x0eboundTbSession\x12\x1f\n" +
	"\vintent_text\x18\b \x01(\tR\n" +
	"intentText\x12#\n" +
	"\rintent_source\x18\t \x01(\tR\fintentSource\x12*\n" +
	"\x11intent_updated_at\x18\n" +
	" \x01(\tR\x0fintentUpdatedAt\"\xb6\x05\n" +
	"\x17PendingApprovalSnapshot\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12%\n" +
	"\x0eparams_inspect\x18\x03 \x01(\tR\rparamsInspect\x12\x1b\n" +
	"\teffect_id\x18\x04 \x01(\tR\beffectId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"tb_session\x18\a \x01(\tR\ttbSession\x12\x17\n" +
	"\acell_id\x18\b \x01(\tR\x06cellId\x12$\n" +
	"\x0efull_tool_name\x18\t \x01(\tR\ffullToolName\x12\x1f\n" +
	"\vpackage_key\x18\n" +
	" \x01(\tR\n" +
	"packageKey\x12#\n" +
	"\rpackage_label\x18\v \x01(\tR\fpackageLabel\x12\x1d\n" +
	"\n" +
	"tool_label\x18\f \x01(\tR\ttoolLabel\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12\"\n" +
	"\fpresentation\x18\x0e \x01(\tR\fpresentation\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vintent_text\x18\x11 \x01(\tR\n" +
	"intentText\x12#\n" +
	"\rintent_source\x18\x12 \x01(\tR\fintentSource\x12*\n" +
	"\x11intent_updated_at\x18\x13 \x01(\tR\x0fintentUpdatedAt\x121\n" +
	"\x14requires_credentials\x18\x14 \x01(\bR\x13requiresCredentials\"\xb1\x01\n" +
	"\x10ApprovalDecision\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12 \n" +
	"\ftool_call_id\x18\x02 \x01(\tR\n" +
	"toolCallId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12,\n" +
	"\x12client_decision_id\x18\x04 \x01(\tR\x10clientDecisionId\x12\x1b\n" +
	"\tqueued_at\x18\x05 \x01(\tR\bqueuedAt\"\x88\x04\n" +
	"\x0eClientSnapshot\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12%\n" +
	"\x0eprepared_tools\x18\x04 \x03(\tR\rpreparedTools\x12=\n" +
	"\fconnected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12<\n" +
	"\flast_sync_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSyncAt\x12W\n" +
	"\x11pending_approvals\x18\a \x03(\v2*.toolbox.daemon.v1.PendingApprovalSnapshotR\x10pendingApprovals\x12\x16\n" +
	"\x06locked\x18\b \x01(\bR\x06locked\x12(\n" +
	"\x10bound_tb_session\x18\t \x01(\tR\x0eboundTbSession\x12\x1f\n" +
	"\vintent_text\x18\n" +
	" \x01(\tR\n" +
	"intentText\x12#\n" +
	"\rintent_source\x18\v \x01(\tR\fintentSource\x12*\n" +
	"\x11intent_updated_at\x18\f \x01(\tR\x0fintentUpdatedAt\"\xc1\x01\n" +
	"\vStateUpdate\x12;\n" +
	"\aclients\x18\x01 \x03(\v2!.toolbox.daemon.v1.ClientSnapshotR\aclients\x12!\n" +
	"\fsecret_epoch\x18\x02 \x01(\tR\vsecretEpoch\x12R\n" +
	"\x12approval_decisions\x18\x03 \x03(\v2#.toolbox.daemon.v1.ApprovalDecisionR\x11approvalDecisions\"$\n" +
	"\x10SecretGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\")\n" +
	"\x11SecretGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\":\n" +
	"\x10SecretSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x13\n" +
	"\x11SecretSetResponse\"'\n" +
	"\x13SecretDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x16\n" +
	"\x14SecretDeleteResponse\"+\n" +
	"\x11SecretListRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"(\n" +
	"\x12SecretListResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"4\n" +
	"\x13SecretUnlockRequest\x12\x1d\n" +
	"\n" +
	"unlock_key\x18\x01 \x01(\tR\tunlockKey\"\x16\n" +
	"\x14SecretUnlockResponse\"3\n" +
	"\x12SecretSetupRequest\x12\x1d\n" +
	"\n" +
	"unlock_key\x18\x01 \x01(\tR\tunlockKey\"8\n" +
	"\x13SecretSetupResponse\x12!\n" +
	"\fbackup_codes\x18\x01 \x03(\tR\vbackupCodes\"\x13\n" +
	"\x11SecretLockRequest\"\x14\n" +
	"\x12SecretLockResponse2\xab\x01\n" +
	"\x0eSessionService\x12G\n" +
	"\x04Ping\x12\x1e.toolbox.daemon.v1.PingRequest\x1a\x1f.toolbox.daemon.v1.PingResponse\x12P\n" +
	"\tSyncState\x12\x1f.toolbox.daemon.v1.SessionState\x1a\x1e.toolbox.daemon.v1.StateUpdate(\x010\x012\xf0\x04\n" +
	"\x12SecretStoreService\x12Y\n" +
	"\x06Unlock\x12&.toolbox.daemon.v1.SecretUnlockRequest\x1a'.toolbox.daemon.v1.SecretUnlockResponse\x12V\n" +
	"\x05Setup\x12%.toolbox.daemon.v1.SecretSetupRequest\x1a&.toolbox.daemon.v1.SecretSetupResponse\x12S\n" +
	"\x04Lock\x12$.toolbox.daemon.v1.SecretLockRequest\x1a%.toolbox.daemon.v1.SecretLockResponse\x12P\n" +
	"\x03Get\x12#.toolbox.daemon.v1.SecretGetRequest\x1a$.toolbox.daemon.v1.SecretGetResponse\x12P\n" +
	"\x03Set\x12#.toolbox.daemon.v1.SecretSetRequest\x1a$.toolbox.daemon.v1.SecretSetResponse\x12Y\n" +
	"\x06Delete\x12&.toolbox.daemon.v1.SecretDeleteRequest\x1a'.toolbox.daemon.v1.SecretDeleteResponse\x12S\n" +
	"\x04List\x12$.toolbox.daemon.v1.SecretListRequest\x1a%.toolbox.daemon.v1.SecretListResponseB8Z6github.com/solidarity-ai/toolbox/daemon/apiv1;daemonv1b\x06proto3"

var (
	file_daemon_apiv1_daemon_proto_rawDescOnce sync.Once
	file_daemon_apiv1_daemon_proto_rawDescData []byte
)

func file_daemon_apiv1_daemon_proto_rawDescGZIP() []byte {
	file_daemon_apiv1_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_apiv1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_apiv1_daemon_proto_rawDesc), len(file_daemon_apiv1_daemon_proto_rawDesc)))
	})
	return file_daemon_apiv1_daemon_proto_rawDescData
}

var file_daemon_apiv1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_daemon_apiv1_daemon_proto_goTypes = []any{
	(*PingRequest)(nil),             // 0: toolbox.daemon.v1.PingRequest
	(*PingResponse)(nil),            // 1: toolbox.daemon.v1.PingResponse
	(*SessionState)(nil),            // 2: toolbox.daemon.v1.SessionState
	(*PendingApprovalSnapshot)(nil), // 3: toolbox.daemon.v1.PendingApprovalSnapshot
	(*ApprovalDecision)(nil),        // 4: toolbox.daemon.v1.ApprovalDecision
	(*ClientSnapshot)(nil),          // 5: toolbox.daemon.v1.ClientSnapshot
	(*StateUpdate)(nil),             // 6: toolbox.daemon.v1.StateUpdate
	(*SecretGetRequest)(nil),        // 7: toolbox.daemon.v1.SecretGetRequest
	(*SecretGetResponse)(nil),       // 8: toolbox.daemon.v1.SecretGetResponse
	(*SecretSetRequest)(nil),        // 9: toolbox.daemon.v1.SecretSetRequest
	(*SecretSetResponse)(nil),       // 10: toolbox.daemon.v1.SecretSetResponse
	(*SecretDeleteRequest)(nil),     // 11: toolbox.daemon.v1.SecretDeleteRequest
	(*SecretDeleteResponse)(nil),    // 12: toolbox.daemon.v1.SecretDeleteResponse
	(*SecretListRequest)(nil),       // 13: toolbox.daemon.v1.SecretListRequest
	(*SecretListResponse)(nil),      // 14: toolbox.daemon.v1.SecretListResponse
	(*SecretUnlockRequest)(nil),     // 15: toolbox.daemon.v1.SecretUnlockRequest
	(*SecretUnlockResponse)(nil),    // 16: toolbox.daemon.v1.SecretUnlockResponse
	(*SecretSetupRequest)(nil),      // 17: toolbox.daemon.v1.SecretSetupRequest
	(*SecretSetupResponse)(nil),     // 18: toolbox.daemon.v1.SecretSetupResponse
	(*SecretLockRequest)(nil),       // 19: toolbox.daemon.v1.SecretLockRequest
	(*SecretLockResponse)(nil),      // 20: toolbox.daemon.v1.SecretLockResponse
	(*timestamppb.Timestamp)(nil),   // 21: google.protobuf.Timestamp
}
var file_daemon_apiv1_daemon_proto_depIdxs = []int32{
	3,  // 0: toolbox.daemon.v1.SessionState.pending_approvals:type_name -> toolbox.daemon.v1.PendingApprovalSnapshot
	21, // 1: toolbox.daemon.v1.ClientSnapshot.connected_at:type_name -> google.protobuf.Timestamp
	21, // 2: toolbox.daemon.v1.ClientSnapshot.last_sync_at:type_name -> google.protobuf.Timestamp
	3,  // 3: toolbox.daemon.v1.ClientSnapshot.pending_approvals:type_name -> toolbox.daemon.v1.PendingApprovalSnapshot
	5,  // 4: toolbox.daemon.v1.StateUpdate.clients:type_name -> toolbox.daemon.v1.ClientSnapshot
	4,  // 5: toolbox.daemon.v1.StateUpdate.approval_decisions:type_name -> toolbox.daemon.v1.ApprovalDecision
	0,  // 6: toolbox.daemon.v1.SessionService.Ping:input_type -> toolbox.daemon.v1.PingRequest
	2,  // 7: toolbox.daemon.v1.SessionService.SyncState:input_type -> toolbox.daemon.v1.SessionState
	15, // 8: toolbox.daemon.v1.SecretStoreService.Unlock:input_type -> toolbox.daemon.v1.SecretUnlockRequest
	17, // 9: toolbox.daemon.v1.SecretStoreService.Setup:input_type -> toolbox.daemon.v1.SecretSetupRequest
	19, // 10: toolbox.daemon.v1.SecretStoreService.Lock:input_type -> toolbox.daemon.v1.SecretLockRequest
	7,  // 11: toolbox.daemon.v1.SecretStoreService.Get:input_type -> toolbox.daemon.v1.SecretGetRequest
	9,  // 12: toolbox.daemon.v1.SecretStoreService.Set:input_type -> toolbox.daemon.v1.SecretSetRequest
	11, // 13: toolbox.daemon.v1.SecretStoreService.Delete:input_type -> toolbox.daemon.v1.SecretDeleteRequest
	13, // 14: toolbox.daemon.v1.SecretStoreService.List:input_type -> toolbox.daemon.v1.SecretListRequest
	1,  // 15: toolbox.daemon.v1.SessionService.Ping:output_type -> toolbox.daemon.v1.PingResponse
	6,  // 16: toolbox.daemon.v1.SessionService.SyncState:output_type -> toolbox.daemon.v1.StateUpdate
	16, // 17: toolbox.daemon.v1.SecretStoreService.Unlock:output_type -> toolbox.daemon.v1.SecretUnlockResponse
	18, // 18: toolbox.daemon.v1.SecretStoreService.Setup:output_type -> toolbox.daemon.v1.SecretSetupResponse
	20, // 19: toolbox.daemon.v1.SecretStoreService.Lock:output_type -> toolbox.daemon.v1.SecretLockResponse
	8,  // 20: toolbox.daemon.v1.SecretStoreService.Get:output_type -> toolbox.daemon.v1.SecretGetResponse
	10, // 21: toolbox.daemon.v1.SecretStoreService.Set:output_type -> toolbox.daemon.v1.SecretSetResponse
	12, // 22: toolbox.daemon.v1.SecretStoreService.Delete:output_type -> toolbox.daemon.v1.SecretDeleteResponse
	14, // 23: toolbox.daemon.v1.SecretStoreService.List:output_type -> toolbox.daemon.v1.SecretListResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_daemon_apiv1_daemon_proto_init() }
func file_daemon_apiv1_daemon_proto_init() {
	if File_daemon_apiv1_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_apiv1_daemon_proto_rawDesc), len(file_daemon_apiv1_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_daemon_apiv1_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_apiv1_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_apiv1_daemon_proto_msgTypes,
	}.Build()
	File_daemon_apiv1_daemon_proto = out.File
	file_daemon_apiv1_daemon_proto_goTypes = nil
	file_daemon_apiv1_daemon_proto_depIdxs = nil
}
