// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: daemon/apiv1/daemon.proto

package daemonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *PingResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type SessionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	PreparedTools []string               `protobuf:"bytes,4,rep,name=prepared_tools,json=preparedTools,proto3" json:"prepared_tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionState) Reset() {
	*x = SessionState{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionState) ProtoMessage() {}

func (x *SessionState) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionState.ProtoReflect.Descriptor instead.
func (*SessionState) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *SessionState) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SessionState) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SessionState) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *SessionState) GetPreparedTools() []string {
	if x != nil {
		return x.PreparedTools
	}
	return nil
}

type ClientSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	PreparedTools []string               `protobuf:"bytes,4,rep,name=prepared_tools,json=preparedTools,proto3" json:"prepared_tools,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	LastSyncAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_sync_at,json=lastSyncAt,proto3" json:"last_sync_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSnapshot) Reset() {
	*x = ClientSnapshot{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSnapshot) ProtoMessage() {}

func (x *ClientSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSnapshot.ProtoReflect.Descriptor instead.
func (*ClientSnapshot) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *ClientSnapshot) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ClientSnapshot) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ClientSnapshot) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ClientSnapshot) GetPreparedTools() []string {
	if x != nil {
		return x.PreparedTools
	}
	return nil
}

func (x *ClientSnapshot) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *ClientSnapshot) GetLastSyncAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncAt
	}
	return nil
}

type StateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*ClientSnapshot      `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_apiv1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_daemon_apiv1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *StateUpdate) GetClients() []*ClientSnapshot {
	if x != nil {
		return x.Clients
	}
	return nil
}

var File_daemon_apiv1_daemon_proto protoreflect.FileDescriptor

const file_daemon_apiv1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x19daemon/apiv1/daemon.proto\x12\x11toolbox.daemon.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vPingRequest\":\n" +
	"\fPingResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\"|\n" +
	"\fSessionState\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12%\n" +
	"\x0eprepared_tools\x18\x04 \x03(\tR\rpreparedTools\"\xfb\x01\n" +
	"\x0eClientSnapshot\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12%\n" +
	"\x0eprepared_tools\x18\x04 \x03(\tR\rpreparedTools\x12=\n" +
	"\fconnected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12<\n" +
	"\flast_sync_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSyncAt\"J\n" +
	"\vStateUpdate\x12;\n" +
	"\aclients\x18\x01 \x03(\v2!.toolbox.daemon.v1.ClientSnapshotR\aclients2\xab\x01\n" +
	"\x0eSessionService\x12G\n" +
	"\x04Ping\x12\x1e.toolbox.daemon.v1.PingRequest\x1a\x1f.toolbox.daemon.v1.PingResponse\x12P\n" +
	"\tSyncState\x12\x1f.toolbox.daemon.v1.SessionState\x1a\x1e.toolbox.daemon.v1.StateUpdate(\x010\x01B8Z6github.com/solidarity-ai/toolbox/daemon/apiv1;daemonv1b\x06proto3"

var (
	file_daemon_apiv1_daemon_proto_rawDescOnce sync.Once
	file_daemon_apiv1_daemon_proto_rawDescData []byte
)

func file_daemon_apiv1_daemon_proto_rawDescGZIP() []byte {
	file_daemon_apiv1_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_apiv1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_apiv1_daemon_proto_rawDesc), len(file_daemon_apiv1_daemon_proto_rawDesc)))
	})
	return file_daemon_apiv1_daemon_proto_rawDescData
}

var file_daemon_apiv1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_daemon_apiv1_daemon_proto_goTypes = []any{
	(*PingRequest)(nil),           // 0: toolbox.daemon.v1.PingRequest
	(*PingResponse)(nil),          // 1: toolbox.daemon.v1.PingResponse
	(*SessionState)(nil),          // 2: toolbox.daemon.v1.SessionState
	(*ClientSnapshot)(nil),        // 3: toolbox.daemon.v1.ClientSnapshot
	(*StateUpdate)(nil),           // 4: toolbox.daemon.v1.StateUpdate
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_daemon_apiv1_daemon_proto_depIdxs = []int32{
	5, // 0: toolbox.daemon.v1.ClientSnapshot.connected_at:type_name -> google.protobuf.Timestamp
	5, // 1: toolbox.daemon.v1.ClientSnapshot.last_sync_at:type_name -> google.protobuf.Timestamp
	3, // 2: toolbox.daemon.v1.StateUpdate.clients:type_name -> toolbox.daemon.v1.ClientSnapshot
	0, // 3: toolbox.daemon.v1.SessionService.Ping:input_type -> toolbox.daemon.v1.PingRequest
	2, // 4: toolbox.daemon.v1.SessionService.SyncState:input_type -> toolbox.daemon.v1.SessionState
	1, // 5: toolbox.daemon.v1.SessionService.Ping:output_type -> toolbox.daemon.v1.PingResponse
	4, // 6: toolbox.daemon.v1.SessionService.SyncState:output_type -> toolbox.daemon.v1.StateUpdate
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_daemon_apiv1_daemon_proto_init() }
func file_daemon_apiv1_daemon_proto_init() {
	if File_daemon_apiv1_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_apiv1_daemon_proto_rawDesc), len(file_daemon_apiv1_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_apiv1_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_apiv1_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_apiv1_daemon_proto_msgTypes,
	}.Build()
	File_daemon_apiv1_daemon_proto = out.File
	file_daemon_apiv1_daemon_proto_goTypes = nil
	file_daemon_apiv1_daemon_proto_depIdxs = nil
}
